//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWorkMusin
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Products
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string manufacturer { get; set; }
        public double price { get; set; }
        public int sale { get; set; }
        public string picture { get; set; }
        public string PriceText
        {
            get
            {
                if (this.sale > 0)
                {
                    string str = this.price.ToString();
                    float? newPrice = (float?)(this.price - (this.price * this.sale / 100));
                    string through = "";
                    foreach (char c in str)
                    {
                        through += c + "\u0336";
                    }
                    //through.Add(TextDecorations.Strikethrough);
                    return ("Старая цена:\n" + through + "\nЦена:\n" + newPrice + "р.");
                }
                else
                {
                    return "Цена:\n" + this.sale + "р.";
                }
            }
        }
        public string Image
        {
            get
            {
                if (this.picture == null)
                {

                    return (Environment.CurrentDirectory + "\\images\\unknown.png");
                }
                else
                {
                    return (Environment.CurrentDirectory + "\\images\\" + this.picture);
                }
            }
        }
        public SolidColorBrush solidColorBrush
        {
            get
            {
                if (this.sale >= 15)
                {
                    SolidColorBrush brush = (SolidColorBrush)(new BrushConverter().ConvertFrom("#7fff00"));
                    return brush;
                }
                else if (this.sale <= 5)
                {
                    SolidColorBrush brush = new SolidColorBrush(Colors.Red);
                    return brush;
                }
                else
                {
                    return Brushes.Transparent;
                }
            }
        }
    }

}
